# https://github.com/shalzz/zola-deploy-action
name: Zola on GitHub Pages

on:
  release:
    types: [published]

jobs:
  build:
    name: Publish site
    runs-on: ubuntu-latest
    steps:
    - name: Checkout release tag
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.release.tag_name }}
    - name: Build and deploy
      uses: shalzz/zola-deploy-action@v0.20.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
